### ISSUE TITLE
BTC-e code support

### ISSUE THREAD

**Issue by noescape00** [brunoamancio/ViolinBTCE#1]
Can you please add support for api methods "CreateCoupon" and "RedeemCoupon" (https://btc-e.com/tapi/docs#CreateCoupon)?

**Comment by noescape00** [comment]
I've added support for those api methods. Do you accept pull requests or you've given up this project?

**Comment by brunoamancio** [comment]
Of course. Make the pull request, I'll check it and accept it, in case everything is fine.

**Comment by brunoamancio** [comment]
Solved in https://github.com/brunoamancio/ViolinBTCE/pull/2
